version: '3.8'
services:
  authorization-server:
    build:
      context: ./springboot-note-authorization-server
      dockerfile: Dockerfile
    image: note-auth-server:0.0.1
    container_name: noteauth
    ports:
      - 8090:8090
    expose:
      - 8090

  api-service:
    build:
      context: ./springboot-note
      dockerfile: Dockerfile
    image: note-resource-server:0.0.1
    container_name: noteresource
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - authorization-server

  react-app:
    build:
      context: ./note-react-app
      dockerfile: Dockerfile
    image: note-react-app:0.0.1
    container_name: noteapp
    ports:
      - 80:80
    expose:
      - 80
    depends_on:
      - api-service

networks:
  default:
    name: note-app-network
