logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.oauth2: DEBUG
        web: DEBUG
    root: INFO
server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:./src/main/resources/demo;AUTO_SERVER=TRUE
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-ui
      settings:
        web-allow-others: true
  jpa:
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create-drop # to ensure data.sql insert successfully each time
    open-in-view: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
    show-sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://127.0.0.1:8090
          # no need to set jwk url by default
          # jwk-set-uri: http://127.0.0.1:8090/oauth2/jwks
  sql:
    init:
      mode: always # load h2 schema and data.sql each time
      platform: h2
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
