logging:
  level:
    org:
      springframework:
        security: INFO
        security.oauth2: INFO
        web: INFO
    root: INFO
server:
  port: 8080
spring:
  datasource:
    #    url: jdbc:h2:./src/main/resources/demo;AUTO_SERVER=TRUE
    #    driver-class-name: org.h2.Driver
    url: jdbc:mysql://localhost:3306/notedb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sa
    password: sapassword
  sql:
    init:
      mode: always # load h2 schema and data.sql each time
#      platform: h2
      platform: mysql
  jpa:
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create-drop # to ensure data.sql insert successfully each time
    open-in-view: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
    show-sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-ui
#      settings:
#        web-allow-others: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://127.0.0.1:8090
          # no need to set jwk url by default
          # jwk-set-uri: http://127.0.0.1:8090/oauth2/jwks

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
note:
  originURI: "http://127.0.0.1/"
