logging:
    level:
        org:
            springframework:
                security: INFO
                security.oauth2: INFO
                web: INFO
        root: INFO
server:
    port: 8080
spring:
    datasource:
        driver-class-name: org.h2.Driver
        password: ''
        url: jdbc:h2:./src/main/resources/demo;AUTO_SERVER=TRUE
        username: sa
    h2:
        console:
            enabled: true
            path: /h2-ui
    jpa:
        defer-datasource-initialization: 'true'
        hibernate:
            ddl-auto: create-drop # to ensure data.sql insert successfully each time
        open-in-view: true
        properties:
            jakarta:
                persistence:
                    sharedCache:
                        mode: ENABLE_SELECTIVE
        show-sql: true
    security:
        oauth2:
            resource-server:
                jwt:
                    issuer-uri: http://127.0.0.1:8090
                    jwk-set-uri: http://127.0.0.1:8090/oauth2/jwks
    sql:
        init:
            mode: always # data.sql initialization
            platform: h2
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui
