logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.oauth2: DEBUG
        web: DEBUG
    root: INFO
server:
  port: 8090
note:
  issuerURI: "http://127.0.0.1:8090"